name: Publish release

on:
  release:
    types: [published]


# Require explicit job permissions
permissions: {}

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Allow use of GitHub OIDC for PyPI authentication
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # https://github.com/pdm-project/setup-pdm/releases/tag/v4.4
      - uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0
        with:
          python-version: 3.12
          cache: true

      - name: Publish distribution package to PyPI
        run: pdm publish
