name: "Scan workflows"

on:
    pull_request:
      branches:
        - "**"
      paths:
        # Run for changes to *any* workflow file
        - ".github/workflows/*.yml"
    push:
      branches:
        - main

# Require explicit job permissions
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Write access needed to upload SARIF scan results
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        # https://github.com/astral-sh/setup-uv/releases/tag/v6.1.0
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb

      - name: Run zizmor 🌈
        # Only scan this repo's workflows, not anything in submodules
        run: uvx zizmor==1.8.0 --format sarif .github > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: workflow-scan.sarif
